baseURL = ""
languageCode = "en-us"
title = "Hugo Serif Theme"
themesDir = "themes"
theme = "hugo serif"
publishDir = "public"

[module.hugoVersion]
extended = true
min = "0.55.0"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.homepage]
  show_contact_box = true
  show_services_button = true

  [params.logo]
  mobile = "images/logo/logo-mobile.svg"
  mobile_height = "36px"
  desktop = "images/logo/logo.svg"
  desktop_height = "36px"
  alt = "Serif - A Hugo Business Theme"

  [params.seo]
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

  [params.team]
  summary_large_truncate = 120

  [params.footer]
  copyright_text = 'Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
